
USE gocareer;

CREATE TABLE COMPANY(
company_id INT AUTO_INCREMENT PRIMARY KEY,
user_name VARCHAR(25) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL,
company_name VARCHAR(20),
industry VARCHAR(255),
tax_number VARCHAR(20) UNIQUE NOT NULL,
address VARCHAR(100) NOT NULL,
email VARCHAR(50) UNIQUE NOT NULL,
phone VARCHAR(20) NOT NULL
);

CREATE TABLE JOB_SEEKER(
job_seeker_id INT AUTO_INCREMENT PRIMARY KEY,
user_name VARCHAR(25) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL,
first_name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
gender ENUM('Male', 'Female', 'Other') NOT NULL,
address VARCHAR(255) NOT NULL,
email VARCHAR(50) UNIQUE NOT NULL,
phone VARCHAR(20) NOT NULL,
CV TEXT NOT NULL
);

CREATE TABLE JOB_POSTING(
job_posting_id INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(100) NOT NULL,
description TEXT NOT NULL,
country VARCHAR(50) NOT NULL,
city VARCHAR(50) NOT NULL
);

CREATE TABLE POST(
post_id INT AUTO_INCREMENT PRIMARY KEY,
company_id INT NOT NULL,
job_posting_id INT NOT NULL,
date DATETIME NOT NULL,
is_active ENUM('Active','Not Active'),
FOREIGN KEY(company_id) REFERENCES COMPANY(company_id) ON DELETE CASCADE,
FOREIGN KEY(job_posting_id) REFERENCES JOB_POSTING(job_posting_id) ON DELETE CASCADE
);

CREATE TABLE APPLIES(
applies_id INT AUTO_INCREMENT PRIMARY KEY,
job_seeker_id INT NOT NULL,
job_posting_id INT NOT NULL,
applies_date DATE NOT NULL,
status ENUM('Evaluation','Accepted','Not Accepted'),
motivation_letter TEXT,
FOREIGN KEY(job_seeker_id) REFERENCES JOB_SEEKER(job_seeker_id) ON DELETE CASCADE,
FOREIGN KEY(job_posting_id) REFERENCES JOB_POSTING(job_posting_id) ON DELETE CASCADE
);

CREATE TABLE MESSAGE(
message_id INT AUTO_INCREMENT PRIMARY KEY,
sender_id INT NOT NULL,
receiver_id INT NOT NULL,
content TEXT,
date_time DATETIME NOT NULL,
FOREIGN KEY(sender_id) REFERENCES COMPANY(company_id) ON DELETE CASCADE,
FOREIGN KEY(receiver_id) REFERENCES JOB_SEEKER(job_seeker_id) ON DELETE CASCADE
);

SELECT*FROM COMPANY;
SELECT*FROM JOB_SEEKER;
SELECT*FROM JOB_POSTING;
SELECT*FROM POST;
SELECT*FROM APPLIES;
SELECT*FROM MESSAGE;